name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'android-*' # Push events to matching v*, i.e. v1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Cache gradle, maven, and konan across builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
            ~/.konan
          key: ${{ runner.os }}-konancache-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties', 'buildSrc/*.kt', 'settings.gradle*', 'gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-konancache-

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Publish Library
        env:
          artifactoryUser: ${{ secrets.ARTIFACTORY_USER }}
          artifactoryPwd: ${{ secrets.ARTIFACTORY_PWD }}
          bintrayVersionName: ${{ github.ref }}
        run: ./gradlew publish
