name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "15.0.1"
#    - name: Build for iOS
#      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MobilePassiveData-Package -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" | xcpretty
#    - name: Run tests for iOS
#      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MobilePassiveData-Package -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" | xcpretty
    - name: Run tests for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test -scheme MobilePassiveData-Package -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" -skipMacroValidation | xcpretty
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9.0"
    - name: Build for macOS
      run: swift build -v
    - name: Run tests for macOS
      run: swift test -v
